version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jralberto
      POSTGRES_PASSWORD: 8689jccs
      POSTGRES_DB: sysGM_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: